- errors.go
- glide.lock
- glide.yaml
- satisfy.go
- solve_test.go
- solver.go
per #5 and #15 
still need to write up an alternate version of string generation for the error types that we pass in. what's done now is just too verbose for inclusion in trace tree output, but it's good when it's the final error, so we need an alternate path.
> Implement tracelog

- constraint_test.go
- constraints.go
- manager_test.go
- result_test.go
- satisfy.go
- selection.go
- sm_adapter.go
- solve_test.go
- solver.go
- version.go
Initially I'd thought this one could be pushed off, but turns out...not so much. It becomes necessary exactly as soon as you've got locked revs (and only revs) coming out of a manifest. We have to assume that'll regularly be the case.
This introduces an apparatus for 'authoritative' constraint ops - that is, if the typical `Matches()`, `MatchesAny()`, or `Intersect()` method fails/returns `none`, the solver - specifically, the `smAdapter` - will reach out to the source manager and find any 'synonyms' for both operands, retry the operation.
Initially, I was handling the cases for this manually. It was easy enough for `Matches()`, but it got nuts for the other two. So, I made `versionTypeUnion` - a union that ORs together a bunch of versions, and itself implements a version. It's *strictly* …
> Allow matching/equivalency across versions with shared underlying revisions

- bridge.go
- example.go
- hash.go
- hash_test.go
- manager_test.go
- project_manager.go
- result_test.go
- solve_basic_test.go
- solve_bimodal_test.go
- solver.go
- source_manager.go
Fixes #50 
Including this information directly in the hash is actually kind of problematic, as it makes implementing tools expressly incompatible with one another. It points to the need for separating out some properties, so that tooling reading a lock file can make more granular decisions about what cross-tool compatibility means.
> Refactor analyzer

- errors.go
- satisfy.go
- solve_basic_test.go
- solve_bimodal_test.go
- solve_test.go
- solver.go
- types.go
Sorta related to #20, but mostly different.
This sets up a system for proper comparison of errors on fixture tests, rather than using a shitty, imprecise abstraction.
Ended up kinda being a prerequisite for #76 because it's just painful adding more error types without this.
> Better handling of solve failures in tests

- bridge.go
- manager_test.go
- solve_basic_test.go
- solver.go
- source.go
- source_manager.go
> Introduce strategic prefetching

- deduce.go
- deduce_test.go
- maybe_source.go
- source_test.go
- vcs_source.go
Fixes #97 
This implementation isn't perfect - at minimum, we ignore the "unstable" suffix on import paths (because there's no clear semantic analogue) - but it's good enough for a first pass, I think.
> Gopkgin filtering

- manifest.go
- solve_basic_test.go
- solve_bimodal_test.go
- solve_test.go
- solver.go
This introduces the notion of a 'required' package: 
* Required packages must be present in any complete solution returned by the solver. 
* Requiring a package that is a logical child of the project root is not an error, but it is a no-op.
* Requiring and ignoring the same package from a manifest is an error.
This is a root-only capability: listing required packages is, thus, a `RootManifest` method.
Addresses #42
> Introduce 'requires'

- manager_test.go
- source_manager.go
Fixes #86, #89
This is also prerequisite to #130, as I'm just not comfortable thinking about a persistent cache until we have tighter control over `SourceMgr` lifecycle
> Source Manager state management, plus signals

- vcs_source.go
Don't show git password prompt not only in terminal but for any `askPass` program.
> Don't show any git password prompt

- _testdata/src/buildtag/invalid.go
- analysis.go
- analysis_test.go
Previously the included test package would have been ignored.
This ensures that the `// +build` is at the beginning of a line
before the package declaration.
> analyze: Fix up detection of // +build

- result.go
- result_test.go
- source.go
- vcs_source.go
As raised in golang/dep#144, we weren't handling exports of bzr or hg repos correctly.
> Export non-git VCS correctly

- analysis.go
- analysis_test.go
> Ignore dirs/files with perms issues in ListPackages

- trace.go
My first attempt at a PR..
Closes https://github.com/sdboyer/gps/issues/129
@sdboyer when you get a chance let me know what you think!
> Removing nested trace output from trace.go

- cmd.go
- manager_test.go
activityBuffers just need a lock when setting timestamps and performing writes.
Fixes #183.
> Fix data race in activityBuffer

- deduce.go
- manager_test.go
This was a little tricky: my company has a private git server hidden behind a VPN. I ran `dep status` while _not_ on the VPN, and `dep` panicked and crashed when it tried to look up the version of one of those private repos. This seemed weird!
It turns out this comes down to an error shadowing bug, deep in the *SourceMgr's futures. The test here panics on master, but passes with this revision.
> Fix err shadowing bug that caused panics for unreachable repos

- maybe_source.go
Instead of errors like this:
```
solve error: No valid source could be created:
failed to set up "", error Unable to retrieve local repo information	failed to set up "", error Unable to update repository	failed to set up "", error Unable to update repository	failed to set up "", error Unable to update repository
```
This changes gives us errors like this:
```
solve error: No valid source could be created:
failed to set up "https://github.com/jmespath/go-jmespath", error Unable to retrieve local repo information	failed to set up "ssh://git@github.com/jmespath/go-jmespath", error Unable to update repository	failed to set up "git://github.com/jmespath/go-jmespath", error Unable to update repository	failed to set up "http://github.com/jmespath/go-jmespath", error Unable to update repository …
```
> Improve error messages then a VCS operation fails.

- circle.yml
- cmd.go
- glide.lock
- glide.yaml
- maybe_source.go
- vcs_repo.go
- vcs_repo_test.go
- vcs_source.go
As discussed in #84, I'll be working on this WIP so you can see if the direction this is going is where you want it to @sdboyer 
The cleaner way to do this, imho, was to wrap each different `vcs.Repo` implementation that is a `vcs.Repo` itself too, so we don't have to reimplement anything. In practice, it has ended up in a lot of copied code from vcs because of not exported code and so on.
I've only implemented the wrapper for git repos so far, so tell me if you want me to keep on this path or do something else entirely.
> Monitored commands

- deduce.go
- deduce_test.go
The current rules for github usernames only allow for alphanumeric
characters or single hyphens and they cannot begin or end with a hyphen.
In the past however github username rules were less strict and we need
to support these (issue #194).
Using the Google BigQuery public github dataset, I've checked the
usernames of all public commits against the currently defined regex in
deduce.go. From these results I've concluded that usernames with
multiple consecutive hyphens and usernames that end with a hyphen were
allowed in the past and do exist. Fortunately these are the only
exceptions I've found, there were no usernames that started with a
hyphen or contained any other special characters.
In addition, this change now also allows one-letter usernames.
> Relax rules for valid github usernames

- cmd.go
The error in runFromCwd that could potentially be returned from the command was ignored here, so I've fixed that.
Another thing I noticed (but haven't fixed here) is that the [unwrapVcsErr](https://github.com/sdboyer/gps/blob/40253bee3efcc001cffe26081e20bc86220e3a17/source_errors.go#L12-L21) function actually doesn't include the [Original](https://github.com/Masterminds/vcs/blob/795e20f901c3d561de52811fb3488a2cb2c8588b/errors.go#L100) error, so a user would still not know exactly why something may have failed.
> Don't ignore error in runFromCwd

- vcs_repo_test.go
Calling `t.Error` is not enough when encountering an error. While this
marks the test as failed, it won't actually prevent the test from
continuing to run with invalid state. I've replaced these instances with
`t.Fatal`.
There looks to be plenty of opportunity to refactor these tests, but
that's better done in a follow up PR. I've made the smallest change
possible to make these tests not panic in case of errors.
See #200.
> Make the vcs_repo tests fail when encountering an error

- constraint_test.go
- hash_test.go
- manager_test.go
- pkgtree/pkgtree_test.go
- result_test.go
- rootdata_test.go
- vcs_source_test.go
- version_queue_test.go
While working on getting Fastwalk (#180) to work correctly (which btw also needs some changes that I'm planning to submit upstream soon), I noticed a bunch of temp dirs were left behind after running all the tests. And while dealing with that I also found some instances of `t.Errorf` followed by `t.FailNow` in the tests that could be replaced with a single call to `t.Fatalf`.
> A bit of cleaning up the tests

- vcs_source.go
```go
all := bytes.Split(bytes.TrimSpace(out), []byte("\n"))
if len(all) == 0 {
}
```
It's a wrong way to check if no data. And it may cause `headrev := Revision(all[0][:40])
` panic.
See example below:
```go
package main
import (
"bytes"
"fmt"
)
func main() {
out := []byte("")
all := bytes.Split(bytes.TrimSpace(out), []byte("\n"))
fmt.Printf("%d %d\n", len(all), len(all[0]))
}
```
It outputs:
```
1 0
```
> Fix empty out data check

- lockdiff.go
- lockdiff_test.go
- version.go
* Move `LockDiff` and related structs.
* Expose `gps.DiffLocks(l1, l2)` and `gps.DiffProjects(p1, p2)`.
* All the TOML related annotation will remain in dep, using the same `rawX` pattern that locks use.
> Move LockDiff from dep into gps
